apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIxMTIwNzAxNTc1OFoXDTMxMTIwNjAxNTc1OFowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANBk
    KCCVVfMP+onHNJKp2SxZ4Q1tp+6xNp/npHKQZXAQcceS/vB6jVpXn3jIChXojpw+
    88CZDNTEhO0ByK1bl5GV7Yh5btCeeL1yRfZBrZR1cZZdWQGlmtcIRHYCSp6j1Fwg
    lC6qY0uHPD1EwJ26W8tjnMo5dakwVmjjpmx9w8ksyf69FNklp11zWfNRfDlSDURh
    PMxurDo8CO/q0ahxu8ER9dpyLfHuepLCqQ2dv+G2Uw7mMZEzEVHWMDrI4+d/z7kU
    tsweGC9kYTZ4fQIBtRrxeGGqedLQQTKaf/fpN67Sh3U11DH0SU3RBpzsOJvGUqoH
    Nc6Gt5NhJZkZe3AIkt0CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQQB3DqXhefWFDdzLM12Q4PgJSD6zANBgkqhkiG9w0BAQsFAAOCAQEAiR82muP/
    zKbjOIO+aafAyakV+XZMwsXOOMJnYV870ylISpc0Uat/Yfj8kMTV7Xc7GbTls9oO
    jdrsrWtLs2fwv5FkyxbSOmTO+2/cqmq3z4xK7jfAmQLt7am6aMH1wnKZAVgTd5QZ
    pt9Jm+I9v4/Ly7CCplx6WCb8U3oyMGY8t8lUgPlCZP0O6oApZ0b6cSXnNwtlK+aB
    q/ocvR/3tvJQ1WdmyefMK+fk37ZwgE1nCDFsZ4WblosO/nWVnqH2U9r1YeLuwVdN
    1SUsAa9TiSsHVWQYwIutBZ4s1qlVCyFDjs0fNpDH24MFdc3bmVvoH7F/SnY1Q/29
    iD8YCYowdequng==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-12-12T03:39:55Z"
  name: kube-root-ca.crt
  namespace: guestbook
