apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1USXdOekF4TlRjMU9Gb1hEVE14TVRJd05qQXhOVGMxT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkJrCktDQ1ZWZk1QK29uSE5KS3AyU3haNFExdHArNnhOcC9ucEhLUVpYQVFjY2VTL3ZCNmpWcFhuM2pJQ2hYb2pwdysKODhDWkROVEVoTzBCeUsxYmw1R1Y3WWg1YnRDZWVMMXlSZlpCclpSMWNaWmRXUUdsbXRjSVJIWUNTcDZqMUZ3ZwpsQzZxWTB1SFBEMUV3SjI2Vzh0am5NbzVkYWt3Vm1qanBteDl3OGtzeWY2OUZOa2xwMTF6V2ZOUmZEbFNEVVJoClBNeHVyRG84Q08vcTBhaHh1OEVSOWRweUxmSHVlcExDcVEyZHYrRzJVdzdtTVpFekVWSFdNRHJJNCtkL3o3a1UKdHN3ZUdDOWtZVFo0ZlFJQnRScnhlR0dxZWRMUVFUS2FmL2ZwTjY3U2gzVTExREgwU1UzUkJwenNPSnZHVXFvSApOYzZHdDVOaEpaa1plM0FJa3QwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRUUIzRHFYaGVmV0ZEZHpMTTEyUTRQZ0pTRDZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFpUjgybXVQLwp6S2JqT0lPK2FhZkF5YWtWK1haTXdzWE9PTUpuWVY4NzB5bElTcGMwVWF0L1lmajhrTVRWN1hjN0diVGxzOW9PCmpkcnNyV3RMczJmd3Y1Rmt5eGJTT21UTysyL2NxbXEzejR4SzdqZkFtUUx0N2FtNmFNSDF3bktaQVZnVGQ1UVoKcHQ5Sm0rSTl2NC9MeTdDQ3BseDZXQ2I4VTNveU1HWTh0OGxVZ1BsQ1pQME82b0FwWjBiNmNTWG5Od3RsSythQgpxL29jdlIvM3R2SlExV2RteWVmTUsrZmszN1p3Z0UxbkNERnNaNFdibG9zTy9uV1ZucUgyVTlyMVllTHV3VmROCjFTVXNBYTlUaVNzSFZXUVl3SXV0Qlo0czFxbFZDeUZEanMwZk5wREgyNE1GZGMzYm1Wdm9IN0YvU25ZMVEvMjkKaUQ4WUNZb3dkZXF1bmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluVXhTSEJqWjBsemVteG5iRVZIZG5sRU1qZHBhMXA0TUY5dU15MDRiMGxQUldOZlVraHFSWEpYUlhNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMW9NbXcxWkNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pTVRjd09ETmhOek10TmprME55MDBaamM0TFdGbU1UZ3RNMkkyTVRFeU1XSTNOR0l4SWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5pQXZ1VklLWEZCbWVIVlFaeE4yeElsZ3k4cEFWTkhkWDVVM0w4ZnFIb0dhMDJXaXFRRVd2Y2pQNl9hejhtUVNIRUxMV3F6cmxJeGtiUFQwUzNlT1pXenU5V09PTlhNZ3NYYkUtZmxHYmJGaFJpZHZRclNmVGUzeWlobFZtRTRrZngwTU5XekZmTkMyU0tDT2dZeWtkUUFvZ1d2djhWMDRTanY1Rnk1TDFjazhJb3B3YkFoVUpPbC1OZk1vZHpKSE9YZ3ZTZ0ROOTB5eGppTUllUFNqTHFhTVdtV25CUzZSSms2MDJOX2FtLVBMVXpVd21lVXp4b25qMV9mZXlpckQyd1oxd1g5WWc1djNKcnVCejRKUHBaMjJHVmc5TGxNZmR4NUdjTnhyd0FmUUNDZVY3TkY5NUxYYkpmSHR5Mk5ldk82WnFsM3paMUhZa1BmMlB6NlF1TUE=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 17083a73-6947-4f78-af18-3b61121b74b1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-12-12T03:39:55Z"
  name: default-token-h2l5d
  namespace: guestbook
type: kubernetes.io/service-account-token
